#!/usr/bin/with-contenv bash

redirect_cmd() {
	if [[ "${DEBUG}" == "true" ]]; then
		"$@"
	else
		"$@" >/dev/null 2>&1
	fi
}

echo "Starting Prowlarr."
redirect_cmd exec s6-setuidgid abc \
	/app/prowlarr/bin/Prowlarr \
	-nobrowser \
	-data=/config
